# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - test
  - build

variables:
  IMAGE_NAME: dev
  IMAGE_TAG: latest

sast:
  stage: test
  image: node:14
  script:
    - npm install
    - npm run test

build-project:
  stage: build
  image: node:14
  script:
    - npm install
    - npm run build
  artifacts:
    untracked: false
    when: on_success
    access: all
    expire_in: "30 days"
